name: cocktail-app
services:
  cocktail_bdd:
    container_name: cocktail_bdd
    image: mariadb:12.0.2
    volumes:
      - cocktail_volume:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: bddname
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--innodb_initialized']
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - cocktail-network
    restart: unless-stopped

  cocktail_back:
    container_name: cocktail-back
    image: ${MONO_PROJECT_BACK}
    ports:
      - 12000:12000
    environment:
      BDD_HOST: cocktail_bdd
      BDD_PORT: 3306
      BDD_NAME: bddname
      BDD_USER: roger
      BDD_PASS: regor
    depends_on:
      cocktail_bdd:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cocktail-network

  cocktail_front:
    container_name: cocktail-front
    image: ${MONO_PROJECT_FRONT}
    ports:
      - 80:80
    networks:
      - cocktail-network
    restart: unless-stopped

volumes:
  cocktail_volume:

networks:
  cocktail-network: